version: "3.12"
services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
      ORACLE_PASSWORD: ${ORACLE_PASSWORD:-Oracle123}
      APP_USER: ${ORACLE_APP_USER:-app_user}
      APP_USER_PASSWORD: ${ORACLE_APP_PASSWORD:-AppUser123}
    ports:
      - "1521:1521"   # SQL*Net
      - "5500:5500"   # EM Express
    healthcheck:
      test: [ "CMD-SHELL", "echo 'select 1 from dual;' | sqlplus -s system/${ORACLE_PASSWORD:-Oracle123}@localhost:1521/XEPDB1 | grep -q '1'" ]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 60s
    volumes:
      - oracle_data:/opt/oracle/oradata  # persistance des données

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi-backend
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
      DB_HOST: oracle-db
      DB_PORT: "1521"
      DB_SERVICE: "XE1"
      DB_USER: ${ORACLE_APP_USER:-app_user}
      DB_PASSWORD: ${ORACLE_APP_PASSWORD:-AppUser123}
      DATABASE_URL: "oracle+oracledb://${ORACLE_APP_USER:-app_user}:${ORACLE_APP_PASSWORD:-AppUser123}@oracle-db:1521/?service_name=XEPDB1"
    depends_on:
      oracle-db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env

volumes:
  oracle_data:
