repos:
  # Petits checks génériques
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  # Formatage
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [ "--line-length=100" ]

  # Lint & auto-fix
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff                    # lint
        args: [ "--fix" ]             # auto-fix quand possible
      - id: ruff-format             # formateur Ruff (complément de Black)

  # Flake8 (souvent redondant avec Ruff, gardé si plugins spécifiques)
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  # Typage statique
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        additional_dependencies: [ "pydantic", "pydantic-settings" ] # typage Pydantic v2
